export const ActionTypes = {
    FETCH_PLAYERS_LOADING: 'FETCH_PLAYERS_LOADING',
    FETCH_PLAYERS_SUCCESS: 'FETCH_PLAYERS_SUCCESS',
    FETCH_PLAYERS_FAILURE: 'FETCH_PLAYERS_FAILURE',
    FETCH_PLAYER_DISCONNECT: 'FETCH_PLAYER_DISCONNECT',
    FETCH_PLAYER_CREATE: 'FETCH_PLAYER_CREATE',
    FETCH_PLAYER_DESTROY: 'FETCH_PLAYER_DESTROY',
};